### PR TITLE
Version uplift for merging EI maintenance branch to master

### PR DESCRIPTION
**Pull request by zburswa**
### Description of the Change
Version uplift for merging EI maintenance branch to master.

### Benefits
By the version EI backend version uplift, a new version will be released in master branch with all the changes present in maintenance branch. This released version can be used by the users.

### Sign-off
Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: swathi.burada@tcs.com

### CODE REVIEW

**Comment by tobiasake** [comment]
Have you tested the MongoDb connection recovery still works.

You test that by starting EI, MongoDb and RabbitMq, easiest to test in Docker or Kubernetes.
1. When everything is up, upload some subscriptions to EI which stores them in MongoDb.
2. Do some GET request on /subscriptions for getting all subscriptions and you should get the subscription you have uploaded.
3. Shutdown/Stop the MongoDb instance.
4. Do some more GET request on /subscriptions entrypoint (maybe 3-4 times). Now you shouldn't get any subscription in response.
5. Start MongoDb again
6. Do some more GET request on /subscriptions entrypoint, if you get response, then MongoDb connection recovery still works.

If do same steps on the EI 2.x release, then Step 6 will/should fail with no response due to the MongoClient object is None by faulty code handling of MongoDbClient object.

You can do a similar test with RabbitMq:
1. Send some events and check the EI consumer queue is consuming the events in the RabbitMq WebUi.
2. Shudown/Stop RabbitMq and wait some seconds. (if possible, remove the queue/exchange eiffel configuration)
3. Start RabbitMq again.
4. Send some more events and check that EI recreates the EI queue in RabbitMq and consumes events again.

Its important that you test the MongoDb connection before doing any release.

**Review by m-linner-ericsson — CHANGES_REQUESTED** [review]
Thank you for contributing to this repository! Please update the [PR template](https://github.com/eiffel-community/.github/blob/master/.github/PULL_REQUEST_TEMPLATE.md) ([Raw version](https://raw.githubusercontent.com/eiffel-community/.github/master/.github/PULL_REQUEST_TEMPLATE.md)) and don't forget to sign off.

**Comment by zburswa** [comment]
> Have you tested the MongoDb connection recovery still works.
> 
> You cam test that by starting EI, MongoDb and RabbitMq, easiest to test in Docker or Kubernetes.
> 
>     1. When everything is up, upload some subscriptions to EI which stores them in MongoDb.
> 
>     2. Do some GET request on /subscriptions for getting all subscriptions and you should get the subscriptions you have uploaded.
> 
>     3. Shutdown/Stop the MongoDb instance.
> 
>     4. Do some more GET request on /subscriptions entry-point (maybe 3-4 times). Now you shouldn't get any subscription in response.
> 
>     5. Start MongoDb again
> 
>     6. Do some more GET request on /subscriptions entry-point, if you get response, then MongoDb connection recovery still works.
> 
> 
> If you do same steps on the EI 2.x release, then Step 6 will/should fail with no response due to the MongoClient object is None by faulty code handling of MongoDbClient object.
> 
> You can do a similar test with RabbitMq:
> 
>     1. Send some events and check the EI consumer queue is consuming the events in the RabbitMq WebUi.
> 
>     2. Shudown/Stop RabbitMq and wait some seconds. (if possible, remove eiffel queue/exchange configuration)
> 
>     3. Start RabbitMq again.
> 
>     4. Send some more events and check that EI recreates the EI queue in RabbitMq and consumes events again.
> 
> 
> Its important that you test the MongoDb connection before doing any release.
ok Tobias. I will test the above scenarios.

**Comment by zburswa** [comment]
> Have you tested the MongoDb connection recovery still works.
> 
> You cam test that by starting EI, MongoDb and RabbitMq, easiest to test in Docker or Kubernetes.
> 
>     1. When everything is up, upload some subscriptions to EI which stores them in MongoDb.
> 
>     2. Do some GET request on /subscriptions for getting all subscriptions and you should get the subscriptions you have uploaded.
> 
>     3. Shutdown/Stop the MongoDb instance.
> 
>     4. Do some more GET request on /subscriptions entry-point (maybe 3-4 times). Now you shouldn't get any subscription in response.
> 
>     5. Start MongoDb again
> 
>     6. Do some more GET request on /subscriptions entry-point, if you get response, then MongoDb connection recovery still works.
> 
> 
> If you do same steps on the EI 2.x release, then Step 6 will/should fail with no response due to the MongoClient object is None by faulty code handling of MongoDbClient object.
> 
> You can do a similar test with RabbitMq:
> 
>     1. Send some events and check the EI consumer queue is consuming the events in the RabbitMq WebUi.
> 
>     2. Shudown/Stop RabbitMq and wait some seconds. (if possible, remove eiffel queue/exchange configuration)
> 
>     3. Start RabbitMq again.
> 
>     4. Send some more events and check that EI recreates the EI queue in RabbitMq and consumes events again.
> 
> 
> Its important that you test the MongoDb connection before doing any release.

I have tested the above scenarios you mentioned in both EI master and maintenance branches. The functionality is working as expected.

**Comment by tobiasake** [comment]
ok

**Comment by m-linner-ericsson** [comment]
Then you only need to update the PR description to match the template I linked in my comment above.

**Comment by zburswa** [comment]
> Then you only need to update the PR description to match the template I linked in my comment above.

I have updated the PR description.

**Comment by m-linner-ericsson** [comment]
@zburswa Thanks. Sorry for being picky could we have your full name and email. For me, it would look like

```
Mattias Linnér mattias.linner@ericsson.com
```

**Comment by zburswa** [comment]
Will raise new pull request

**Pull request closed without merging**
