### PR TITLE
fix by replacing id with _id

### PR DESCRIPTION
**Pull request by saif-ericsson**
### Applicable Issues
Closes https://github.com/eiffel-community/eiffel-intelligence/issues/441

This is because Eiffel Intelligence doesn't find the resulting aggregation from the database.
The key to search for should be "_id" not "id" - since we can't expect all and every custom rule set to put an "id" in the root of the aggregation.

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by:

### CODE REVIEW

**Comment by Christoffer-Cortes** [comment]
A test could be to use a custom rule that doesn't extract any information from the start event so that just the general aggregation information is in the object. Then try to fetch it using the start event id. That should be successful with this fix.

**Comment by e-pettersson-ericsson** [comment]
> SAIF: If there is one, need to be improved

Just to be clear then: have you tested this functionality locally/manually? Since I don't see any tests affected in this PR that is why I'm asking, to make sure this change doesn't break anything unforeseen.

**Comment by saif-ericsson** [comment]
> A test could be to use a custom rule that doesn't extract any information from the start event so that just the general aggregation information is in the object. Then the test aggregation should fetch the object using the start event id. That should be successful with this fix.

**Comment by saif-ericsson** [comment]
> > A test could be to use a custom rule that doesn't extract any information from the start event so that just the general aggregation information is in the object. Then the test aggregation should fetch the object using the start event id. That should be successful with this fix.

I have created a test for for the two untested methods that will cover this comment as well.

**Pull request merged**
